### ISSUE TITLE
Cannot compute shortest path

### ISSUE THREAD

**Issue by Art-Ev** [AequilibraE/AequilibraE-GUI#182]
**Describe the bug**

Traceback (most recent call last):
              File "%FolderProfile%/python/plugins\AequilibraE\paths_procedures\show_shortest_path_dialog.py", line 154, in produces_path
              self.res.compute_path(int(self.path_from.text()), int(self.path_to.text()))
              File "%FolderProfile%\python\plugins\AequilibraE\aequilibrae\aequilibrae\paths\results\path_results.py", line 88, in compute_path
              self.skims[self.graph.all_nodes, :] = self._skimming_array[:-1, :]
             IndexError: index 1066 is out of bounds for axis 0 with size 1066

**To Reproduce**
Use shortest path dialog: 
For example trying to find shortest (distance) path from 387 to 1067 with [St_Varent.zip](https://github.com/AequilibraE/AequilibraE-GUI/files/8462386/St_Varent.zip)

**Desktop (please complete the following information):**
 - OS: windows 10
 - QGIS Version 3.22

**Comment by pedrocamargo** [comment]
I was able to reproduce the issue, and the network is definitely correct, as I was able to compute a skim matrix between all centroids (two of which are the nodes mentioned in the issue)

![image](https://user-images.githubusercontent.com/7377666/163804326-47252d93-2385-49d3-ae65-07f160ac0647.png)

I was also able to reproduce that issue with the Python library, so this seems to be a deeper problem.

Doing some deeper research, I was able to determine that this only occurs **when the largest node_id is a centroid**. I am not sure why this does not happen with Sioux-Falls, for example.

![image](https://user-images.githubusercontent.com/7377666/163806344-3fb68d9e-b1d7-47cb-a3ad-7c768dbae6de.png)

I think this is the case to transfer this issue to the Python library's repository. Are you happy for me to do that, @Art-Ev ?

**Comment by Art-Ev** [comment]
@pedrocamargo
Sure, do so! (I'm noting the trick to continue testing)
